export const INTERACTION_SNAPSHOT_MAX_ELEMENTS = 120;
export const INTERACTION_CAPTURE_SETTLE_MS = 120;
export const INTERACTION_PROMPT_RETRY_SHRINK_FACTOR = 0.9;
export const INTERACTION_PROMPT_MAX_RETRY_ATTEMPTS = 8;
